name: CD

#on:
#  pull_request:
#    types: [closed]
#    branches:
#      - "main"

on:
  push:
    branches:
      - "*"
      -
jobs:
  cd:
    name: Publish to NPM
    runs-on: ubuntu-latest
#    if: contains(github.head_ref, 'release/')
    timeout-minutes: 10
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.7

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.16.0

      - name: Get version
        id: get_version
        run: |
          VERSION=`node -p "require('./package.json').version"`
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Build the code
        run: npm run build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"

      - name: Config git
        if: steps.tag_exist.outputs.exist == 0
        run: |
          git config --global user.email "contact@dov118.dev"
          git config --global user.name "dov118"

      - name: Set tag
        if: steps.tag_exist.outputs.exist == 0
        run: |
          git tag ${{ steps.get_version.outputs.version }}
          git push --tags

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.version }} --title "Release ${{ steps.get_version.outputs.version }}" --generate-notes --latest
